erDiagram
    ALERTS one to zero or more COMMENTS : writes
    ALERTS one to one or more AUDIT_EVENTS : captures
    ALERTS zero or one to one VERIFICATIONS : verifies
    NOMIS_ALERTS zero or one to one ALERTS : "converts via sync"
ALERTS {
    long id PK
    uuid alert_uuid "This is the ID we expose."
    varchar alert_type
    varchar alert_code
    varchar offender_id
    varchar authorised_by
    timestamptz valid_from
    timestamptz valid_to
    timestamptz removed_at "This is how we distinguish a soft delete."
}
VERIFICATIONS {
    long id PK
    long alert_id FK
    text action
    varchar verified_by
    timestamptz verified_at
}
AUDIT_EVENTS {
    long id PK
    long alert_id FK
    varchar event_description
    varchar created_at
    varchar created_by
    varchar created_by_captured_name
}
COMMENTS {
    long id PK
    text comment
    long alert_id FK
    timestamptz created_at
    varchar created_by
}

NOMIS_ALERTS {
    long nomis_alert_id PK
    json nomis_alert_data
    long alert_id FK
    long offender_book_id
    int alert_seq
    timestamptz upserted_at
    timestamptz removed_at

}


