erDiagram
    alert one to zero or more comment : writes
    alert one to one or more audit_event : captures
    alert_type one to one or more alert_code : categorises
    alert many to one alert_code : "categorised by"

alert {
    long alert_id PK
    uuid alert_uuid "This is the ID we expose."
    varchar prison_number
    long alert_code_id FK
    text description
    varchar authorised_by
    date active_from
    date active_to
    timestamp deleted_at "This is how we distinguish a soft delete."
}

comment {
    long comment_id PK
    uuid comment_uuid
    long alert_id FK
    text comment
    timestamp created_at
    varchar created_by
    varchar created_by_display_name
}

audit_event {
    long id PK
    long alert_id FK
    varchar event_description
    varchar created_at
    varchar created_by
    varchar created_by_captured_name
}

alert_type {
    long alert_type_id PK
    varchar code
    varchar description
    int list_sequence
    timestamp created_at
    varchar created_by
    timestamp modified_at
    varchar modified_by
    timestamp deactivated_at
    varchar deactivated_by
}

alert_code {
    long alert_code_id PK
    long alert_type_id FK
    varchar code
    varchar description
    int list_sequence
    timestamp created_at
    varchar created_by
    timestamp modified_at
    varchar modified_by
    timestamp deactivated_at
    varchar deactivated_by
}
