#
# The "-local" profile is for running the API service locally against pre-existing
# docker containers that are listening on known port numbers for hmpps-auth (8090) and
# a postgres database (5432).
#

# Most values are inherited from - application.yml - except the following:

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          public-key-location: classpath:local-public-key.pub

  jpa:
    show-sql: true

# Container-provider local services
api:
  base:
    url:
      hmpps-auth: http://localhost:8090/auth
      manage-users: http://localhost:8111
      prisoner-search: http://localhost:8112

hmpps.sqs:
  provider: localstack
  localstackUrl: http://localhost:4567
  queues:
    publish:
      queueName: publish-queue
      dlqName: publish-dlq
  topics:
    hmppseventtopic:
      arn: arn:aws:sns:eu-west-2:000000000000:hmpps-event-topic