package uk.gov.justice.digital.hmpps.hmppsalertsapi.resource

const val ROLE_PRISONER_ALERTS__RO = "ROLE_PRISONER_ALERTS__RO"
const val ROLE_PRISONER_ALERTS__RW = "ROLE_PRISONER_ALERTS__RW"
const val ROLE_PRISONER_ALERTS__PRISONER_ALERTS_ADMINISTRATION_UI = "ROLE_PRISONER_ALERTS__PRISONER_ALERTS_ADMINISTRATION_UI"

// Sync/migration roles
const val ROLE_NOMIS_ALERTS = "ROLE_NOMIS_ALERTS"
