---
# Per environment values which override defaults in hmpps-alerts-api/values.yaml

generic-service:

  ingress:
    host: alerts-api-preprod.hmpps.service.justice.gov.uk

  env:
    SENTRY_ENVIRONMENT: preprod
    APPLICATIONINSIGHTS_CONFIGURATION_FILE: applicationinsights.dev.json
    API_BASE_URL_HMPPS_AUTH: "https://sign-in-preprod.hmpps.service.justice.gov.uk/auth"
    API_BASE_URL_MANAGE_USERS: "https://manage-users-api-preprod.hmpps.service.justice.gov.uk"
    API_BASE_URL_PRISONER_SEARCH: "https://prisoner-search-preprod.prison.service.justice.gov.uk"
    EVENTS_BASE_URL: "https://alerts-api-preprod.hmpps.service.justice.gov.uk"
    SERVICE_ACTIVE_PRISONS: "***"
    SERVICE_UI_URL: "https://alerts-ui-preprod.hmpps.service.justice.gov.uk"
# CloudPlatform AlertManager receiver to route prometheus alerts to slack
# See https://user-guide.cloud-platform.service.justice.gov.uk/documentation/monitoring-an-app/how-to-create-alarms.html#creating-your-own-custom-alerts
generic-prometheus-alerts:
  alertSeverity: hmpps-prisoner-profile-non-prod # sent to Slack channel #connect-dps-non-prod-alerts
  businessHoursOnly: true
  sqsOldestAlertQueueNames:
    - "hmpps-move-and-improve-preprod-hmpps_alerts_domain_events_queue"
  sqsNumberAlertQueueNames:
    - "hmpps-move-and-improve-preprod-hmpps_alerts_domain_events_dlq"
  sqsAlertsOldestThreshold: 10
  sqsAlertsTotalMessagesThreshold: 1
  rdsAlertsDatabases:
    cloud-platform-08f5f8988104952a: 'Prisoner Alerts API'
  rdsAlertsConnectionThreshold: 100
