---
# Per environment values which override defaults in hmpps-alerts-api/values.yaml

generic-service:
  replicaCount: 2

  ingress:
    host: alerts-api-dev.hmpps.service.justice.gov.uk

  env:
    SENTRY_ENVIRONMENT: dev
    SPRING_PROFILES_ACTIVE: dev
    APPLICATIONINSIGHTS_CONFIGURATION_FILE: applicationinsights.dev.json
    API_BASE_URL_HMPPS_AUTH: "https://sign-in-dev.hmpps.service.justice.gov.uk/auth"
    API_BASE_URL_MANAGE_USERS: "https://manage-users-api-dev.hmpps.service.justice.gov.uk"
    API_BASE_URL_PRISONER_SEARCH: "https://prisoner-search-dev.prison.service.justice.gov.uk"
    EVENTS_BASE_URL: "https://alerts-api-dev.hmpps.service.justice.gov.uk"
    SERVICE_ACTIVE_PRISONS: "LEI"
    SERVICE_UI_URL: "https://alerts-ui-dev.hmpps.service.justice.gov.uk"
# CloudPlatform AlertManager receiver to route prometheus alerts to slack
# See https://user-guide.cloud-platform.service.justice.gov.uk/documentation/monitoring-an-app/how-to-create-alarms.html#creating-your-own-custom-alerts
generic-prometheus-alerts:
  alertSeverity: hmpps-alerts-api-non-prod # sent to Slack channel #move-and-improve-alerts-non-prod
  businessHoursOnly: true

data_analytics:
  extract: true
