---
# Per environment values which override defaults in hmpps-alerts-api/values.yaml

generic-service:
  ingress:
    host: alerts-api.hmpps.service.justice.gov.uk

  env:
    HMPPS_AUTH_URL: https://sign-in.hmpps.service.justice.gov.uk/auth
    USER_MANAGEMENT_API_URL: https://manage-users-api.hmpps.service.justice.gov.uk
    PRISONER_SEARCH_API_URL: https://prisoner-search.prison.service.justice.gov.uk

# CloudPlatform AlertManager receiver to route prometheus alerts to slack
# See https://user-guide.cloud-platform.service.justice.gov.uk/documentation/monitoring-an-app/how-to-create-alarms.html#creating-your-own-custom-alerts
generic-prometheus-alerts:
  alertSeverity: digital-prison-service
