---
# Per environment values which override defaults in hmpps-alerts-api/values.yaml

generic-service:
  replicaCount: 2

  ingress:
    host: alerts-api-dev.hmpps.service.justice.gov.uk

  env:
    APPLICATIONINSIGHTS_CONFIGURATION_FILE: applicationinsights.dev.json
    HMPPS_AUTH_URL: https://sign-in-dev.hmpps.service.justice.gov.uk/auth
    USER_MANAGEMENT_API_URL: https://manage-users-api-dev.hmpps.service.justice.gov.uk
    PRISONER_SEARCH_API_URL: https://prisoner-search-dev.prison.service.justice.gov.uk

# CloudPlatform AlertManager receiver to route prometheus alerts to slack
# See https://user-guide.cloud-platform.service.justice.gov.uk/documentation/monitoring-an-app/how-to-create-alarms.html#creating-your-own-custom-alerts
generic-prometheus-alerts:
  alertSeverity: digital-prison-service-dev
